name: hNear
version: "1.2"
main: ru.he3hauka.hnear.Main
api-version: '1.16'
softdepend: [PlaceholderAPI,LuckPerms]
depend: [PlaceholderAPI,LuckPerms]
author: He3Hauka
website: https://t.me/hplugin
commands:
  near:
